### ISSUE TITLE
Openstack DLO missing segments

### ISSUE THREAD

**Issue by blankdots** [CSCfi/swift-concurrent-upload#1]
We need to modify
https://github.com/CSCfi/swift-concurrent-upload/blob/master/concurrent_rclone_rcat.sh#L45-L52 so that we have full support over DLO in Openstack swift

**Comment by teemukataja** [comment]
![Screenshot from 2021-10-06 10-17-22](https://user-images.githubusercontent.com/17040963/136356554-dd2da8d5-652e-413f-8fdb-756850d6a629.png)
### Issue
`koe.fq.zst` was uploaded with `rclone` and it can't be downloaded
`test5.bin.c4gh` is a SLO that was uploaded with `swift` and it can be downloaded
`test_dlo.bin` is a DLO that was uploaded with `swift` and it can be downloaded

### Details
`koe.fq.zst` has form
```
filename/timestamp/file_size/segment_number
```
and `test_dlo.bin` has form
```
filename/timestamp/file_size/segment_size/segment_number
```
I think the missing `/segment_size/` in the DLO path is breaking the download concatenation

### Swift
`swift` command used to upload DLO
```
swift --os-auth-token $OS_AUTH_TOKEN upload $CONTAINER -S 1048576 test_dlo.bin
```
where `-S 1048576` is the segment size in bytes

### Other
unrelated, but noticed, that the SLO file is similar to DLO, but has an additional `/slo/` in the path

**Comment by teemukataja** [comment]
Kimmo reports, that `swift download` is able to download the DLO, but Pouta UI, Allas UI and ObjectStorage API are unable to serve the file

**Comment by blankdots** [comment]
closing as `wontfix` as this is does not present as a problem any more
